exclude: '^$|settings|scripts'
fail_fast: false
repos:

# - repo: https://github.com/asottile/add-trailing-comma
#   rev: v0.7.1
#   hooks:
#     - id: add-trailing-comma

- repo: git@github.com:pre-commit/pre-commit-hooks
  rev: v2.1.0
  hooks:
    # Disabled because yapf is better for our purpose
    # - id: autopep8-wrapper
    - id: check-added-large-files
    - id: debug-statements
    - id: double-quote-string-fixer
    - id: end-of-file-fixer
      exclude: 'static'
    - id: fix-encoding-pragma
      args: ['--remove']
    - id: check-merge-conflict
    - id: check-symlinks
    - id: trailing-whitespace
    - id: mixed-line-ending
      args: ['--fix=lf']

- repo: git@github.com:humitos/mirrors-autoflake.git
  rev: v1.1
  hooks:
    - id: autoflake
      args: ['--in-place', '--remove-all-unused-imports', '--remove-unused-variable']

# When calling `pre-commit autoupdate`, this repo needs to be commented because it fails
- repo: git@github.com:FalconSocial/pre-commit-python-sorter.git
  rev: b57843b0b874df1d16eb0bef00b868792cb245c2  # higher than 1.0.4 (latest release)
  hooks:
    - id: python-import-sorter
      args: ['--silent-overwrite']
      exclude: 'wsgi.py'

- repo: git@github.com:myint/docformatter.git
  rev: v1.1
  hooks:
    - id: docformatter
      args: ['--in-place', '--wrap-summaries=80', '--wrap-descriptions=80', '--pre-summary-newline']
